benimProjem/urls.py
from django.conf.urls import url
from django.contrib import admin
from rango import views
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r"^$", views.anasayfa, name="anasayfa"),
    url(r"^rango/", include("rango.urls")),
    url(r"^hesaplar/register/$", views.kayit, name="registration_register"),
    url(r"^hesaplar/", include("registration.backends.simple.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rango/urls.py
from django.conf.urls import url
from rango import views

app_name    = "rango"
urlpatterns = [
    url(r"^$", views.anasayfa, name="anasayfa"),
    url(r"^about/", views.about, name="hakkimda"),
    url(r"^kategori/(?P<kategoriAdresi>[\w\-]+)/$", views.sayfalarıGöster, name="sayfalarıGöster"),
    url(r"^kategori-ekle/$", views.kategoriEkle, name="kategori-ekle"),
    url(r"^(?P<kategoriAdresi>[\w\-]+)/sayfa-ekle/$", views.sayfaEkle, name="sayfa-ekle"),
    url(r"^arama/$", views.arama, name="arama"),
    url(r"^git/", views.sayfaGit, name="git"),
]

rango/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User


class Kategori(models.Model):
    kategoriIsim        = models.CharField(max_length=128, unique=True)
    kategoriGoruntuleme = models.IntegerField(default=0)
    kategoriBegeni      = models.IntegerField(default=0)
    slug                = models.SlugField(blank=True, unique=True)
    türkçeKarakter      = "ığüşöçĞÜŞİÖÇ"
    karşıKarakter       = "igusocGUSIOC"
    çeviri              = str.maketrans(türkçeKarakter, karşıKarakter)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.kategoriIsim.translate(self.çeviri))
        super().save(*args, **kwargs)

    class Meta:
        verbose_name_plural = "Kategoriler"

    def __str__(self):
        return self.kategoriIsim


class Sayfa(models.Model):
    kategori         = models.ForeignKey(Kategori)
    sayfaIsim        = models.CharField(max_length=128)
    sayfaGoruntuleme = models.IntegerField(default=0)
    sayfaUrl         = models.URLField()

    def kategoriDef(self):
        return self.kategori

    def sayfaIsimDef(self):
        return self.sayfaIsim

    def sayfaUrlDef(self):
        return self.sayfaUrl
    kategoriDef.short_description  = "Sektör"
    sayfaIsimDef.short_description = "Web Sitesi"
    sayfaUrlDef.short_description  = "Url Adresi"

    class Meta:
        verbose_name_plural = "Sayfalar"

    def __str__(self):
        return self.sayfaIsim


class KullaniciBilgisi(models.Model):
    kullanici   = models.OneToOneField(User)
    website     = models.URLField(blank=True, help_text='Web Siteniz')
    profilResim = models.ImageField(blank=True, help_text='Profil Resminiz')

    def __str__(self):
        return self.kullanici.username

    class Meta:
        verbose_name_plural = "Kullanıcılar"

rango/views.py
# View 'lar içinde response vermek için çeşitli yardımcı metaryaller içe aktarılıyor.
# Başlangıç
from django.shortcuts import (
                              render,
                              reverse,
                              redirect,
                              )
from django.http import (
                         HttpResponseRedirect,
                         HttpResponse,
                         )
# Bitiş

# Kategori ve Sayfa modeli içeri akratılıyor.
from rango.models import (
                          Kategori,
                          Sayfa,
                          KullaniciBilgisi,
                          )
# Form verileri içeri aktarılıyor.
from rango.formlar import (
                           KategoriForm,
                           SayfaForm,
                           KullaniciForm,
                           KullaniciBilgisiForm
                           )
# İşlem yapabilmek için sisteme login olunması gereken View 'lar için
# login_required bezeyicisi sisteme eklendi.
from django.contrib.auth.decorators import login_required
# Zaman bilgisini Cookie 'ler der kullanabilmek içni datetime kütüphanesi içe aktarılıyor.
from datetime import datetime
from django.contrib.auth.models import User
from bingArama import bingAra

def anasayfa(request):
    ziyaretSayaci(request)
    kullanici = None
    if str(request.user) is not "AnonymousUser":
        kullaniciNesnesi = User.objects.get(username=request.user)
        kullanici = KullaniciBilgisi.objects.get(kullanici=kullaniciNesnesi)
    kategoriler = Kategori.objects.order_by("-kategoriBegeni")[:5]
    sayfalar    = Sayfa.objects.order_by("-sayfaGoruntuleme")[:5]
    içerik      = {
        "kategoriler": kategoriler,
        "sayfalar"   : sayfalar,
        "kullanici"  : kullanici,
    }
    cevap = render(request, "rango/index.html", context=içerik)
    return cevap


def about(request):
    ziyaretSayaci(request)
    şablonDeğişkenleri = {"isimsoyisim": "Ünal TUTAY"}
    return render(request, "rango/about.html", context=şablonDeğişkenleri)


def sayfalarıGöster(request, kategoriAdresi):
    ziyaretSayaci(request)
    içerik = dict()
    try:
        kategori           = Kategori.objects.get(slug=kategoriAdresi)
        sayfalar           = Sayfa.objects.filter(kategori=kategori)
        içerik["kategori"] = kategori
        içerik["sayfalar"] = sayfalar
    except Kategori.DoesNotExist:
        içerik["kategori"] = None
        içerik["sayfalar"] = None
        print("{} adresiyle eşleşen herhangi bir kategori bulunamadı.".format(
            kategoriAdresi))
    return render(request, "rango/kategoriler.html", context=içerik)


@login_required
def kategoriEkle(request):
    ziyaretSayaci(request)
    formBilgisi = KategoriForm()
    if request.method == "POST":
        formBilgisi = KategoriForm(request.POST)
        if formBilgisi.is_valid():
            formBilgisi.save(commit=True)
            return anasayfa(request)
        else:
            print("Hata yazdırılıyor:", formBilgisi.errors)
    içerik = {"bilgiler": formBilgisi}
    return render(request, "rango/kategori-ekle.html", context=içerik)


@login_required
def sayfaEkle(request, kategoriAdresi):
    ziyaretSayaci(request)
    try:
        kategori = Kategori.objects.get(slug=kategoriAdresi)
    except Kategori.DoesNotExist:
        kategori = None
    formBilgi = SayfaForm()
    if request.method == "POST":
        formBilgi = SayfaForm(request.POST)
        if formBilgi.is_valid():
            if kategori:
                sayfa          = formBilgi.save(commit=False)
                sayfa.kategori = kategori
                sayfa.save()
                return HttpResponseRedirect(
                    reverse(
                        "rango:sayfalarıGöster",
                        kwargs={"kategoriAdresi": kategoriAdresi},
                    )
                )
        else:
            print(formBilgi.errors)
    içerik = {"formBilgi": formBilgi, "kategori": kategori}
    return render(request, "rango/sayfa-ekle.html", context=içerik)


def ziyaretSayaci(request):
    ziyaretSayisiCookie = int(request.session.get("ziyaretSayisi", "1"))
    sonZiyaretCookie    = request.session.get("sonZiyaret", str(datetime.today()))
    sonZiyaretNesne     = datetime.strptime(sonZiyaretCookie[:-7], "%Y-%m-%d %H:%M:%S")
    if (datetime.now() - sonZiyaretNesne).seconds > 0:
        ziyaretSayisiCookie += 1
        request.session["sonZiyaret"] = str(datetime.today())
    else:
        request.session["sonZiyaret"] = sonZiyaretCookie
    request.session["ziyaretSayisi"] = ziyaretSayisiCookie
    return ziyaretSayisiCookie


def kayit(request):
    hata = dict()
    kullanici = KullaniciForm()
    profil = KullaniciBilgisiForm()
    if request.method == "POST":
        kullanici = KullaniciForm(request.POST)
        profil = KullaniciBilgisiForm(request.POST)
        if kullanici.is_valid() and profil.is_valid():
            kullanici = kullanici.save(commit=False)
            profil = profil.save(commit=False)
            if "profilResim" in request.FILES:
                profil.profilResim  = request.FILES["profilResim"]
                if profil.profilResim.name.endswith("jpg") or profil.profilResim.name.endswith("jpeg"):
                    if profil.profilResim.width > 340 or profil.profilResim.height > 340:
                        hata.update(
                                    {
                                    "boyut" : "Sadece 340x340 boyutundaki resimlere izin verilmektedir."
                                    }
                                    )
                    else:
                        kullanici.save()
                        profil.kullanici = kullanici
                        profil.save()
                        return HttpResponseRedirect(reverse("registration_complete"))
                else:
                    hata.update(
                                {
                                "uzantı" : "Sadece jpeg yada jpg uzantılı profil resmi yükleyebilirsiniz."
                                }
                                )
            else:
                kullanici.save()
                profil.kullanici = kullanici
                profil.save()
                return HttpResponseRedirect(reverse("registration_complete"))
        else:
            if not kullanici.is_valid():
                hata.update(kullanici.errors)
                print(kullanici.errors)
            if not profil.is_valid():
                hata.update(profil.errors)
                print(profil.errors)
    içerik = {
            "kullanici": kullanici,
            "profil": profil,
            "hata": hata
            }
    return render(request, "registration/registration_form.html", içerik)


def arama(request):
    sorgulananVeri = None
    sorgu = None
    if request.method == "POST":
        sorgu = request.POST["sorgu"].strip()
        sorgulananVeri = bingAra(sorgu)
    return render(
                  request,
                  "rango/arama.html",
                  {
                    "sorgulananVeri": sorgulananVeri,
                    "sorgu": sorgu,
                  }
                  )

@login_required
def sayfaGit(request):
    if request.method == "GET":
        sayfaId = request.GET.get("sayfaId")
        try:
            sayfa   = Sayfa.objects.get(id=sayfaId)
            sayfa.sayfaGoruntuleme += 1
            sayfa.save()
            return redirect(sayfa.sayfaUrl)
        except Exception:
            return HttpResponseRedirect(reverse("rango:anasayfa"))

templates/rango/about.html
{% extends "rango/taban.html" %}

{% load staticfiles %}

{% block baslik_blok %}
    Hakkımda
{% endblock %}

{% block vucut_blok %}
    <h1>Hakkımda Sayfasına Hoşgeldiniz :)</h1><br>
    Bu projenin parçaları {{ isimsoyisim }} tarafından bir araya getirilmiştir.<br>
{% endblock %}

{% block alt_blok %}
    <img src="{{ MEDIA_URL }}kedi.jpg" alt="Sevimli kedicik :)" /><br>
{% endblock %}

templates/rango/arama.html
{% extends "rango/taban.html" %}
{% load staticfiles %}
{% block stilDosyalari %}
  <style type="text/css">
  .alignleft {
  float: left;
  display: block;
  }
  .ekDuzenleme{
  overflow: auto;
  }
  .text-center {
  text-align: center; }
  </style>
{% endblock stilDosyalari %}
{% block vucut_blok %}
  <div class="container">
    <h3 class="text-center">Arama Motoruna Hoşgeldiniz</h3>
    <form method="post" action=".">
      <div class="row">
        <div class="col-lg-12">
          <div class="input-group input-group-lg">
            {% csrf_token %}
            {% if sorgu %}
              <input type="text" class="form-control input-lg" id="search-church" placeholder="{{ sorgu }}" name="sorgu">
            {% else %}
              <input type="text" class="form-control input-lg" id="search-church" placeholder="ne aramak istemiştiniz?" name="sorgu">
            {% endif %}
            <span class="input-group-btn">
              <button class="btn btn-default btn-lg" type="submit">Search</button>
            </span>
          </div>
        </div>
      </div>
    </form>
    {% if sorgulananVeri %}
      <div class="list-group">
        {% for veri in sorgulananVeri %}
          <a href="{{ veri.url }}" class="list-group-item list-group-item-action">
            <h5 class="list-group-item-heading">{{ veri.name }}</h5>
            <p class="list-group-item-text ekDuzenleme">
              {% if veri.image %}
                <img src="{{ veri.image }}" class="rounded alignleft" height="100px" width="100px">
              {% endif %}
              {{ veri.description }}
            </p>
          </a>
        {% endfor %}
      </div>
    {% endif %}
  </div>
{% endblock vucut_blok %}

templates/rango/index.html
{% extends "rango/taban.html" %}
{% load staticfiles %}
{% block stilDosyalari %}
  <link href="{% static "ozel_bootstrap/narrow-jumbotron.css" %}" rel="stylesheet">
{% endblock stilDosyalari %}
{% block baslik_blok %}
  Anasayfa
{% endblock %}
{% block vucut_blok %}
  <div class="jumbotron">
    <h1 class="display-3">Siteme hoşgeldiniz!</h1>
    {% if user.is_authenticated %}
      <p class="lead">Merhaba, {{ user.first_name }} {{ user.last_name }} :)</p>
      {% if kullanici.profilResim %}
        <img src="{{ MEDIA_URL }}{{ kullanici.profilResim }}" class="rounded-circle" width="150px" height="150px">
      {% else %}
        Şuanda profil resminiz bulunmuyor, profil resmi eklemek için üyelik sayfanıza gidebilirsiniz.
      {% endif %}
    {% else %}
      Siteye henüz giriş yapmadınız. Aşağıdaki üye ol butonuna tıklayarak sitemize hemen üye olmaya başlayabilirsiniz.
      <p><a class="btn btn-lg btn-success" href="{% url "registration_register" %}" role="button">Üye Ol</a></p>
    {% endif %}
  </div>
  <div class="row marketing">
    <div class="col-lg-6">
      <h4>En çok beğenilen kategoriler</h4>
      <p>
        {% if kategoriler %}
          <ul class="list-group">
            {% for kategori in kategoriler %}
              <li class="list-group-item">
                <span class="tag tag-default tag-pill float-xs-right">{{ kategori.kategoriBegeni }}</span>
                <a href="{% url "rango:sayfalarıGöster" kategori.slug %}">{{ kategori }}</a>
              </li>
            {% endfor %}
          </ul>
        </p>
      {% else %}
        <p>Şuan görüntülenecek bir kategori bulunmamaktadır!</p>
      {% endif %}
    </div>
    <div class="col-lg-6">
      <h4>En çok görüntülenen sayfalar</h4>
      <p>
        {% if sayfalar %}
          <ul class="list-group">
            {% for sayfa in sayfalar %}
              <li class="list-group-item">
                <span class="tag tag-default tag-pill float-xs-right">{{ sayfa.sayfaGoruntuleme }}</span>
                <a href="{% url "rango:git" %}?sayfaId={{ sayfa.id }}">{{ sayfa.sayfaIsim }}</a>
              </li>
            {% endfor %}
          </ul>
        {% else %}
          <p>Şuanda görüntülenecek sayfa bulunamadı!</p>
        {% endif %}
      </p>
    </div>
  </div>
{% endblock %}
{% block alt_blok %}
  <!--   <center><img src="{% static "images/kertenkele.jpg" %}" alt="Rango: Yeşil Kertenle" /></center> -->
{% endblock %}

templates/rango/kategori-ekle.html
{% extends "rango/taban.html" %}

{% load staticfiles %}
{% block stilDosyalari %}
    <link href="{% static "bootstrap/examples/signin/signin.css" %}" rel="stylesheet">
{% endblock stilDosyalari %}
{% block baslik_blok %}
    Kategori Ekle
{% endblock %}

{% block vucut_blok %}
        <h3 class="form-signin-heading">Kategori Ekleme Sayfası</h3>
    <form method="post" action="{% url "rango:kategori-ekle" %}">
        {% csrf_token %}
        {% for gizli in bilgiler.hidden_fields %}
            {{ gizli }}
        {% endfor %}
        {% for gorunur in bilgiler.visible_fields %}
            <p>
                {{ gorunur.error }}
                {{ gorunur.help_text }}
                {{ gorunur }}
            </p>
        {% endfor %}
        <input class="btn btn-primary" type="submit" name="Gönder" value="Gönder" />
    </form>
    {% if bilgiler.errors %}
        {{ bilgiler.errors }}
    {% endif %}
{% endblock %}

templates/rango/kategoriler.html
{% extends "rango/taban.html" %}

{% load staticfiles %}

{% block baslik_blok %}
    {% if kategori %}
        {{ kategori }}
    {% endif %}
{% endblock %}

{% block vucut_blok %}
    {% if kategori %}
        <h1>{{ kategori }}</h1>
        {% if sayfalar %}
            <ul class="list-group">
                {% for sayfa in sayfalar %}
                    <li class="list-group-item">
                    <span class="tag tag-default tag-pill float-xs-right">{{ sayfa.sayfaGoruntuleme }}</span>
                    <a href="{% url "rango:git" %}?sayfaId={{ sayfa.id }}" title="{{ sayfa.sayfaIsim }}">{{ sayfa.sayfaIsim }}</a>
                    </li>
                {% endfor %}
            </ul>
        {% else %}
            <strong>{{ kategori }} kategorisinde sayfa mevcut değil.</strong>
        {% endif %}
    {% else %}
        <strong>Ulaşmaya çalıştığınız kategori mevcut değil!</strong>
    {% endif %}
{% endblock %}

{% block link_blok %}
    <a class="nav-item nav-link" href="{% url "rango:sayfa-ekle" kategori.slug %}">Sayfa Ekle</a>
{% endblock %}

templates/rango/sayfa-ekle.html
{% extends "rango/taban.html" %}
{% load staticfiles %}
{% block stilDosyalari %}
    <link href="{% static "bootstrap/examples/signin/signin.css" %}" rel="stylesheet">
{% endblock stilDosyalari %}
{% block baslik_blok %}
    Sayfa Ekle
{% endblock %}
{% block vucut_blok %}
    {% if kategori %}
        <h3 class="form-signin-heading">
        Şuanda <a href="rango/{{ kategori.slug }}">{{ kategori.kategoriIsim }}</a> kategorisine sayfa ekliyorsunuz.
        </h3>
        <form method="post" action="{% url "rango:sayfa-ekle" kategori.slug %}">
            {% csrf_token %}
            {% for gizli in formBilgi.hidden_fields %}
                {{ gizli }}
            {% endfor %}
            {% for gorunur in formBilgi.visible_fields %}
                <p>
                    {{ gorunur.errors }}
                    {{ gorunur.help_text }}
                    {{ gorunur }}
                </p>
            {% endfor %}
            {% if formBilgi.errors %}
                {{ formBilgi.errors }}
            {% endif %}
            <input class="btn btn-primary" type="submit" name="Gönder" value="Gönder" />
        </form>
    {% else %}
        <strong>Sayfa eklemek için önce kategori belirlemelisiniz!</strong>
    {% endif %}
{% endblock %}

templates/rango/sidebar_kategori_tag.html
<div class="list-group">
  {% if kategoriler %}
    {% for kategori in kategoriler %}
      <a class="list-group-item" href="{% url "rango:sayfalarıGöster" kategori.slug %}" title="{{ kategori }}">{{ kategori }}</a>
    {% endfor %}
  {% else %}
    <li><strong>Kategori bulunmamaktadır!</strong></li>
  {% endif %}
  </div>

templates/rango/taban - backup.html
<!DOCTYPE html>
{% load staticfiles %}
{% load kategori_ozel_etiket %}
<html lang="tr">
    <head>
        <meta charset="utf-8">
        <title>
            {% block baslik_blok %}
                Django ile Tango Nasıl Yapılır
            {% endblock %}
        </title>
    <style type="text/css">
        body,td,th {
	font-size: 18px;
	font-family: Consolas, "Andale Mono", "Lucida Console", "Lucida Sans Typewriter", Monaco, "Courier New", monospace;
	font-style: normal;
	font-weight: normal;
	color: #00D800;
        }
        body {
	background-color: #000000;
        }
        a {
        font-size: 18px;
        color: #2CC300;
        }
        a:link {
	text-decoration: none;
	color: #00D800;
        }
        a:visited {
	text-decoration: none;
	color: #00D800;
        }
        a:hover {
	text-decoration: none;
	color: #00D800;
        }
        a:active {
            text-decoration: none;
        }
    </style>
    </head>
    <body>
        {% if user.is_authenticated %}
            Merhaba, {{ user.first_name }} {{ user.last_name }} :)
        {% else %}
            Sisteme henüz giriş yapmadınız!
        {% endif %}
        <br>
        {% if request.session %}
           {% if request.session.ziyaretSayisi %}
           Ziyaret sayınız : {{ request.session.ziyaretSayisi }}
           {% endif %}
        {% else %}
            Tarayıcınızda Cookie kapalı! Sitemizden daha çok faydalanmak için cookie 'leri açınız!
        {% endif %}
        <hr>
        {% block kategori_blok %}
            {% kategori_listesi %}
        {% endblock %}
        <hr>
        <div>
        <!-- Sayfa vücudunu oluşturan ana kodların bloğu -->
        <!-- BAŞLANGIÇ -->
            {% block vucut_blok %}
                Burası html sayfa gövdesinin varsayılan öğesidir.
            {% endblock %}
        <!-- BİTİŞ -->
        </div>
        <hr>
        <div>
            <ul>
                <li><a href="{% url "rango:anasayfa" %}" title="Anasayfa">Anasayfa</a> </li>
                <li><a href="{% url "rango:hakkimda" %}" title="Hakkımda">Hakkımda</a> </li>
                {% if user.is_authenticated %}
                    {% block link_blok %}
                    {% endblock %}
                    <li><a href="{% url "rango:kategori-ekle" %}" title="Kategori Ekle">Kategori Ekle</a> </li>
                    <li><a href="{% url "auth_password_change" %}" title="Şifre Değiştir">Şifre Değiştir</a> </li>
                    <li><a href="{% url "rango:kategori-ekle" %}" title="Kategori Ekle">Kategori Ekle</a> </li>
                    <li><a href="{% url "auth_password_reset" %}" title="Şifre Sıfırla">Şifre Sıfırla</a></li>
                    <li><a href="{% url "auth_logout" %}?next=/rango/" title="Çıkış Yap">Çıkış Yap</a></li>
                {% else %}
                    <li><a href="{% url "registration_register" %}" title="Kullanıcı Kayıt">Kullanıcı Kayıt</a></li>
                    <li><a href="{% url "auth_login" %}" title="Giriş yap">Giriş Yap</a></li>
                {% endif %}
            </ul>
            {% block alt_blok %}
            {% endblock %}
        </div>
    </body>
</html>

templates/rango/taban.html
<!DOCTYPE html>
{% load staticfiles %}
{% load kategori_ozel_etiket %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{% static "bootstrap/favicon.ico" %}">
    <title>Rango - {% block baslik_blok %} Django ile Tango Nasıl Yapılır {% endblock %}</title>
    <!-- Bootstrap core CSS -->
    <link href="{% static "bootstrap/dist/css/bootstrap.min.css" %}" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="{% static "ozel_bootstrap/dashboard.css" %}" rel="stylesheet">
  {% block stilDosyalari %}{% endblock stilDosyalari %}
</head>
<body>
  <nav class="navbar navbar-dark navbar-fixed-top bg-inverse">
    <button type="button" class="navbar-toggler hidden-sm-up" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar" aria-label="Toggle navigation"></button>
    <a class="navbar-brand" href="/">Rango</a>
    <div id="navbar">
      <nav class="nav navbar-nav float-xs-left">
        <a class="nav-item nav-link" href="{% url "rango:anasayfa" %}">Anasayfa</a>
        <a class="nav-item nav-link" href="{% url "rango:hakkimda" %}">Hakkımızda</a>
        <a class="nav-item nav-link" href="{% url "rango:arama" %}">Arama Yap</a>
        {% if user.is_authenticated %}
          <a class="nav-item nav-link" href="{% url "rango:kategori-ekle" %}">Kategori Ekle</a>
        {% block link_blok %}{% endblock link_blok %}
        <a class="nav-item nav-link" href="{% url "auth_logout" %}">Çıkış Yap</a>
      {% else %}
        <a class="nav-item nav-link" href="{% url "auth_login" %}">Giriş Yap</a>
        <a class="nav-item nav-link" href="{% url "registration_register" %}">Kullanıcı Kayıt</a>
      {% endif %}
    </nav>
  </div>
</nav>
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-3 col-md-2 sidebar">
      {% block kategori_blok %}
        {% kategori_listesi %}
      {% endblock %}
    </div>
    <div class="col-sm-9 offset-sm-3 col-md-10 offset-md-2 main">
      {% if request.session %}
        {% if request.session.ziyaretSayisi %}
          <div class="alert alert-info" role="alert">
            <strong>Ziyaret sayınız : </strong>{{ request.session.ziyaretSayisi }}
          </div>
        {% endif %}
      {% else %}
        <p><strong>Tarayıcınızda Cookie kapalı! Sitemizden daha çok faydalanmak için cookie 'leri açınız!</strong></p>
      {% endif %}
      {% block vucut_blok %}
        Burası html sayfa gövdesinin varsayılan öğesidir.
      {% endblock %}
      {% block alt_blok %}
      {% endblock alt_blok %}
    </div>
  </div>
</div>
<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.0.0/jquery.min.js" integrity="sha384-THPy051/pYDQGanwU6poAc/hOdQxjnOEXzbT+OuUAFqNqFjL+4IGLBgCJC3ZOShY" crossorigin="anonymous"></script>
<script>window.jQuery || document.write('<script src="{% static "bootstrap/assets/js/vendor/jquery.min.js" %}"><\/script>')</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.2.0/js/tether.min.js" integrity="sha384-Plbmg8JY28KFelvJVai01l8WyZzrYWG825m+cZ0eDDS1f7d/js6ikvy1+X+guPIB" crossorigin="anonymous"></script>
<script src="{% static "bootstrap/dist/js/bootstrap.min.js" %}"></script>
<!-- Just to make our placeholder images work. Don't actually copy the next line! -->
<script src="{% static "bootstrap/assets/js/vendor/holder.min.js" %}"></script>
<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
<script src="{% static "bootstrap/assets/js/ie10-viewport-bug-workaround.js" %}"></script>
</body>
</html>